2023-03-06 19:38:03,038 INFO    StreamThr :4045 [internal.py:wandb_internal():90] W&B internal server running at pid: 4045, started at: 2023-03-06 19:38:03.037647
2023-03-06 19:38:03,040 DEBUG   HandlerThread:4045 [handler.py:handle_request():144] handle_request: status
2023-03-06 19:38:03,064 INFO    WriterThread:4045 [datastore.py:open_for_write():85] open: /home/filippo/Desktop/Project/Experiments/JacoRLDR/sac/wandb/run-20230306_193803-89r1ji6r/run-89r1ji6r.wandb
2023-03-06 19:38:03,065 DEBUG   SenderThread:4045 [sender.py:send():334] send: header
2023-03-06 19:38:03,085 DEBUG   SenderThread:4045 [sender.py:send():334] send: run
2023-03-06 19:38:03,827 INFO    SenderThread:4045 [dir_watcher.py:__init__():216] watching files in: /home/filippo/Desktop/Project/Experiments/JacoRLDR/sac/wandb/run-20230306_193803-89r1ji6r/files
2023-03-06 19:38:03,827 INFO    SenderThread:4045 [sender.py:_start_run_threads():1068] run started: 89r1ji6r with start time 1678099083.052426
2023-03-06 19:38:03,828 DEBUG   SenderThread:4045 [sender.py:send_request():361] send_request: summary_record
2023-03-06 19:38:03,828 INFO    SenderThread:4045 [sender.py:_save_file():1319] saving file wandb-summary.json with policy end
2023-03-06 19:38:03,830 DEBUG   HandlerThread:4045 [handler.py:handle_request():144] handle_request: check_version
2023-03-06 19:38:03,831 DEBUG   SenderThread:4045 [sender.py:send_request():361] send_request: check_version
2023-03-06 19:38:04,075 DEBUG   HandlerThread:4045 [handler.py:handle_request():144] handle_request: run_start
2023-03-06 19:38:04,094 DEBUG   HandlerThread:4045 [system_info.py:__init__():31] System info init
2023-03-06 19:38:04,095 DEBUG   HandlerThread:4045 [system_info.py:__init__():46] System info init done
2023-03-06 19:38:04,095 INFO    HandlerThread:4045 [system_monitor.py:start():151] Starting system monitor
2023-03-06 19:38:04,095 INFO    SystemMonitor:4045 [system_monitor.py:_start():116] Starting system asset monitoring threads
2023-03-06 19:38:04,095 INFO    HandlerThread:4045 [system_monitor.py:probe():172] Collecting system info
2023-03-06 19:38:04,096 INFO    SystemMonitor:4045 [interfaces.py:start():168] Started cpu
2023-03-06 19:38:04,097 INFO    SystemMonitor:4045 [interfaces.py:start():168] Started disk
2023-03-06 19:38:04,098 INFO    SystemMonitor:4045 [interfaces.py:start():168] Started gpu
2023-03-06 19:38:04,099 INFO    SystemMonitor:4045 [interfaces.py:start():168] Started memory
2023-03-06 19:38:04,100 INFO    SystemMonitor:4045 [interfaces.py:start():168] Started network
2023-03-06 19:38:04,105 ERROR   gpu       :4045 [interfaces.py:monitor():129] Failed to sample metric: Not Supported
2023-03-06 19:38:04,105 ERROR   gpu       :4045 [interfaces.py:monitor():129] Failed to sample metric: Not Supported
2023-03-06 19:38:04,124 DEBUG   HandlerThread:4045 [system_info.py:probe():195] Probing system
2023-03-06 19:38:04,136 DEBUG   HandlerThread:4045 [system_info.py:_probe_git():180] Probing git
2023-03-06 19:38:04,167 DEBUG   HandlerThread:4045 [system_info.py:_probe_git():188] Probing git done
2023-03-06 19:38:04,167 DEBUG   HandlerThread:4045 [system_info.py:probe():241] Probing system done
2023-03-06 19:38:04,167 DEBUG   HandlerThread:4045 [system_monitor.py:probe():181] {'os': 'Linux-5.15.0-67-generic-x86_64-with-debian-bullseye-sid', 'python': '3.7.16', 'heartbeatAt': '2023-03-06T10:38:04.124252', 'startedAt': '2023-03-06T10:38:03.001839', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'train.py', 'codePath': 'sac/train.py', 'git': {'remote': 'git@github.com:filyps98/JacoRLDR.git', 'commit': 'd640c383eed864dce639ff53101c072765167b24'}, 'email': 'pippo.ronco@gmail.com', 'root': '/home/filippo/Desktop/Project/Experiments/JacoRLDR', 'host': 'filippo-X510UQ', 'username': 'filippo', 'executable': '/home/filippo/miniconda3/envs/robot/bin/python', 'cpu_count': 2, 'cpu_count_logical': 4, 'cpu_freq': {'current': 2575.02925, 'min': 400.0, 'max': 3500.0}, 'cpu_freq_per_core': [{'current': 2900.0, 'min': 400.0, 'max': 3500.0}, {'current': 2900.0, 'min': 400.0, 'max': 3500.0}, {'current': 2900.0, 'min': 400.0, 'max': 3500.0}, {'current': 1600.117, 'min': 400.0, 'max': 3500.0}], 'disk': {'total': 96.18362426757812, 'used': 78.76362228393555}, 'gpu': 'NVIDIA GeForce 940MX', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce 940MX', 'memory_total': 2147483648}], 'memory': {'total': 7.649127960205078}}
2023-03-06 19:38:04,168 INFO    HandlerThread:4045 [system_monitor.py:probe():182] Finished collecting system info
2023-03-06 19:38:04,168 INFO    HandlerThread:4045 [system_monitor.py:probe():185] Publishing system info
2023-03-06 19:38:04,168 DEBUG   HandlerThread:4045 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2023-03-06 19:38:04,168 DEBUG   HandlerThread:4045 [system_info.py:_save_pip():67] Saving pip packages done
2023-03-06 19:38:04,168 DEBUG   HandlerThread:4045 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2023-03-06 19:38:04,830 INFO    Thread-13 :4045 [dir_watcher.py:_on_file_created():275] file/dir created: /home/filippo/Desktop/Project/Experiments/JacoRLDR/sac/wandb/run-20230306_193803-89r1ji6r/files/wandb-summary.json
2023-03-06 19:38:04,831 INFO    Thread-13 :4045 [dir_watcher.py:_on_file_created():275] file/dir created: /home/filippo/Desktop/Project/Experiments/JacoRLDR/sac/wandb/run-20230306_193803-89r1ji6r/files/requirements.txt
2023-03-06 19:38:04,831 INFO    Thread-13 :4045 [dir_watcher.py:_on_file_created():275] file/dir created: /home/filippo/Desktop/Project/Experiments/JacoRLDR/sac/wandb/run-20230306_193803-89r1ji6r/files/conda-environment.yaml
2023-03-06 19:38:06,106 ERROR   gpu       :4045 [interfaces.py:monitor():129] Failed to sample metric: Not Supported
2023-03-06 19:38:06,107 ERROR   gpu       :4045 [interfaces.py:monitor():129] Failed to sample metric: Not Supported
2023-03-06 19:38:08,107 ERROR   gpu       :4045 [interfaces.py:monitor():129] Failed to sample metric: Not Supported
2023-03-06 19:38:08,107 ERROR   gpu       :4045 [interfaces.py:monitor():129] Failed to sample metric: Not Supported
2023-03-06 19:38:08,572 DEBUG   HandlerThread:4045 [system_info.py:_save_conda():86] Saving conda packages done
2023-03-06 19:38:08,573 INFO    HandlerThread:4045 [system_monitor.py:probe():187] Finished publishing system info
2023-03-06 19:38:08,577 DEBUG   HandlerThread:4045 [handler.py:handle_request():144] handle_request: status_report
2023-03-06 19:38:08,577 DEBUG   SenderThread:4045 [sender.py:send():334] send: files
2023-03-06 19:38:08,578 INFO    SenderThread:4045 [sender.py:_save_file():1319] saving file wandb-metadata.json with policy now
2023-03-06 19:38:08,832 INFO    Thread-13 :4045 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/filippo/Desktop/Project/Experiments/JacoRLDR/sac/wandb/run-20230306_193803-89r1ji6r/files/conda-environment.yaml
2023-03-06 19:38:08,833 INFO    Thread-13 :4045 [dir_watcher.py:_on_file_created():275] file/dir created: /home/filippo/Desktop/Project/Experiments/JacoRLDR/sac/wandb/run-20230306_193803-89r1ji6r/files/wandb-metadata.json
2023-03-06 19:38:09,466 INFO    Thread-16 :4045 [upload_job.py:push():143] Uploaded file /tmp/tmp_ngpbrj8wandb/k0fr7pbh-wandb-metadata.json
2023-03-06 19:38:10,106 ERROR   cpu       :4045 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=4021)
2023-03-06 19:38:10,109 ERROR   cpu       :4045 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=4021)
2023-03-06 19:38:10,110 ERROR   memory    :4045 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=4021)
2023-03-06 19:38:10,110 ERROR   memory    :4045 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=4021)
2023-03-06 19:38:10,111 ERROR   gpu       :4045 [interfaces.py:monitor():129] Failed to sample metric: Not Supported
2023-03-06 19:38:10,111 ERROR   gpu       :4045 [interfaces.py:monitor():129] Failed to sample metric: Not Supported
2023-03-06 19:38:11,077 INFO    MainThread:4045 [internal.py:handle_exit():77] Internal process exited
